Attribute VB_Name = "mXRef"
Option Explicit

'Cross Reference Listing for DataBaseUtil (Project)
'
'   fDBUtil (Form; 31 + 445 = 476 Lines)
'       AdjustBackcolor (Private Sub or Function)
'           AdjustBackcolor (L464 C13)
'           Form_Resize (L262 C11)
'           RefreshOverlays (L452 C9)
'       Bookmark (Private Variable)
'           (L31 C9)
'           btAdd_Click (L97 C13)
'           btAdd_Click (L97 C25)
'           btAdd_Click (L129 C20)
'           btAdd_Click (L129 C31)
'       btAdd_Click (Private Sub or Function)
'           btAdd_Click (L93 C13)
'       btDelete_Click (Private Sub or Function)
'           btDelete_Click (L140 C13)
'       btOpen_Click (Private Sub or Function)
'           btOpen_Click (L154 C13)
'       btSQL_Click (Private Sub or Function)
'           btSQL_Click (L185 C13)
'       CB_ISDROPPED (Private Constant)
'           (L19 C15)
'           tmr_Timer (L342 C34)
'       cbAttri_DropDown (Private Sub or Function)
'           cbAttri_DropDown (L33 C13)
'       cbTables_Click (Private Sub or Function)
'           btOpen_Click (L179 C13)
'           cbTables_Click (L68 C13)
'       ckTop_Click (Private Sub or Function)
'           ckTop_Click (L39 C13)
'       ckTrueFalse_KeyDown (Private Sub or Function)
'           ckTrueFalse_KeyDown (L49 C13)
'       ckTrueFalse_MouseUp (Private Sub or Function)
'           ckTrueFalse_MouseUp (L55 C13)
'       CurrentFieldIndex (Private Variable)
'           (L25 C9)
'           txtValue_GotFocus (L355 C5)
'           txtValue_LostFocus (L365 C25)
'           txtValue_LostFocus (L368 C27)
'       dcNav_MouseDown (Private Sub or Function)
'           dcNav_MouseDown (L219 C13)
'       dcNav_Reposition (Private Sub or Function)
'           dcNav_Reposition (L225 C13)
'       EM_GETLINECOUNT (Private Constant)
'           (L18 C15)
'           AdjustBackcolor (L467 C31)
'       FalseText (Private Constant)
'           (L22 C15)
'           ckTrueFalse_MouseUp (L62 C67)
'       FieldType (Private Variable)
'           (L27 C9)
'           grdData_Click (L278 C9)
'           grdData_Click (L280 C9)
'           grdData_Click (L282 C9)
'           grdData_Click (L284 C9)
'           grdData_Click (L286 C9)
'           grdData_Click (L288 C9)
'           grdData_Click (L290 C9)
'           grdData_Click (L292 C9)
'           grdData_Click (L294 C9)
'           grdData_Click (L296 C9)
'           grdData_Click (L301 C78)
'           grdData_Click (L309 C31)
'       Form_Load (Private Sub or Function)
'           Form_Load (L231 C13)
'       Form_Resize (Private Sub or Function)
'           cbTables_Click (L86 C5)
'           Form_Resize (L237 C13)
'       Form_Unload (Private Sub or Function)
'           Form_Unload (L268 C13)
'       grdData_Click (Private Sub or Function)
'           btOpen_Click (L175 C13)
'           btSQL_Click (L211 C19)
'           cbTables_Click (L88 C5)
'           grdData_Click (L274 C13)
'           tmr_Timer (L348 C9)
'       grdData_Scroll (Private Sub or Function)
'           grdData_Scroll (L334 C13)
'       HWND_NOTTOPMOST (Private Constant)
'           (L13 C15)
'           ckTop_Click (L44 C28)
'       HWND_TOPMOST (Private Constant)
'           (L14 C15)
'           ckTop_Click (L42 C28)
'       i (Private Variable)
'           (L26 C9)
'           btAdd_Click (L100 C19)
'           btAdd_Click (L101 C32)
'           btAdd_Click (L125 C20)
'           btOpen_Click (L160 C7)
'           btOpen_Click (L163 C8)
'           btOpen_Click (L169 C17)
'           btOpen_Click (L170 C49)
'           btOpen_Click (L171 C58)
'           btOpen_Click (L173 C18)
'           Form_Resize (L240 C7)
'           Form_Resize (L242 C28)
'           Form_Resize (L243 C25)
'           Form_Resize (L244 C23)
'           Form_Resize (L246 C26)
'           Form_Resize (L250 C24)
'           grdData_Click (L302 C13)
'           grdData_Click (L304 C78)
'           grdData_Click (L306 C85)
'           grdData_Click (L308 C85)
'           grdData_Click (L308 C153)
'           grdData_Click (L311 C95)
'           grdData_Click (L318 C85)
'           grdData_Click (L318 C153)
'           grdData_Click (L321 C14)
'           RefreshGrid (L387 C13)
'           RefreshGrid (L388 C25)
'           RefreshGrid (L388 C60)
'           RefreshGrid (L390 C45)
'           RefreshGrid (L401 C48)
'           RefreshGrid (L403 C48)
'           RefreshGrid (L408 C14)
'       LastSQL (Private Variable)
'           (L29 C9)
'           btSQL_Click (L190 C89)
'           btSQL_Click (L199 C19)
'           btSQL_Click (L200 C35)
'           btSQL_Click (L205 C43)
'           cbAttri_DropDown (L35 C23)
'           cbTables_Click (L73 C9)
'           cbTables_Click (L74 C25)
'       Margin (Private Variable)
'           (L24 C9)
'           Form_Load (L233 C5)
'           Form_Resize (L240 C24)
'           Form_Resize (L240 C33)
'           Form_Resize (L242 C48)
'       MoveOverlays (Private Sub or Function)
'           Form_Resize (L261 C11)
'           grdData_Click (L326 C5)
'           grdData_Scroll (L336 C5)
'           MoveOverlays (L415 C13)
'           RefreshGrid (L410 C5)
'       NewSQL (Private Variable)
'           (L30 C9)
'           btSQL_Click (L190 C15)
'           btSQL_Click (L191 C18)
'           btSQL_Click (L199 C29)
'       RefreshGrid (Private Sub or Function)
'           btAdd_Click (L133 C15)
'           btDelete_Click (L147 C17)
'           btSQL_Click (L210 C19)
'           cbTables_Click (L85 C5)
'           dcNav_Reposition (L227 C5)
'           RefreshGrid (L378 C13)
'       RefreshOverlays (Private Sub or Function)
'           grdData_Click (L327 C5)
'           RefreshGrid (L411 C5)
'           RefreshOverlays (L442 C13)
'           tmr_Timer (L347 C9)
'       SendMessage (Private Sub or Function)
'           (L11 C26)
'           AdjustBackcolor (L467 C12)
'           tmr_Timer (L342 C8)
'       SetWindowPos (Private Sub or Function)
'           (L10 C21)
'           ckTop_Click (L42 C9)
'           ckTop_Click (L44 C9)
'       SWP_NOMOVE (Private Constant)
'           (L15 C15)
'           ckTop_Click (L42 C68)
'           ckTop_Click (L44 C71)
'       SWP_NOSIZE (Private Constant)
'           (L16 C15)
'           ckTop_Click (L42 C54)
'           ckTop_Click (L44 C57)
'       tmr_Timer (Private Sub or Function)
'           tmr_Timer (L340 C13)
'       TrueText (Private Constant)
'           (L21 C15)
'           ckTrueFalse_MouseUp (L62 C57)
'           RefreshOverlays (L456 C41)
'       TTT (Private Variable)
'           (L28 C9)
'           RefreshOverlays (L444 C5)
'           RefreshOverlays (L450 C28)
'           RefreshOverlays (L458 C28)
'       txtValue_GotFocus (Private Sub or Function)
'           txtValue_GotFocus (L353 C13)
'       txtValue_LostFocus (Private Sub or Function)
'           dcNav_MouseDown (L221 C5)
'           Form_Unload (L270 C5)
'           txtValue_LostFocus (L359 C13)
'       WM_USER (Private Constant)
'           (L17 C15)
'           (L18 C43)
'           (L19 C43)
'
'   mXRef (Module; 203 + 0 = 203 Lines)
'
'End of Cross Reference Listing for DataBaseUtil
'Created by Ulli's VB Cross Reference Version 1.2.14
'Copyright © 2000 - 2001 UMGEDV GmbH

':) Ulli's Code Formatter V2.3 (02.09.2001 16:10:56) 203 + 0 = 203 Lines
